services:
  frontend:
    build: .
    ports:
      - "8080:80"
      
  database-h2:
    image: oscarfonts/h2
    ports:
      - "8086:81"
      - "9092:9092"
    volumes:
      - ./h2-data:/opt/h2-data # Persistenza dati
    environment:
      - H2_OPTIONS=-ifNotExists
    networks:
      - h2-network
  
networks:
  h2-network:
    driver: bridge
    

