apiVersion: v1
kind: ConfigMap
metadata:
  name: info-portale-ford
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="it">
    <head>
        <meta charset="UTF-8">
        <title>Portale Ford 2</title>
        <style>
            body { font-family: sans-serif; background-color: #003478; color: white; text-align: center; padding-top: 50px; }
            .container { border: 2px solid white; display: inline-block; padding: 20px; border-radius: 10px; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Portale Ford v2</h1>
            <p>Benvenuto! Questa pagina è servita da un pod Nginx su Kubernetes.</p>
            <p>Gestito con successo tramite <strong>ArgoCD</strong>.</p>
        </div>
    </body>
    </html>