name: GitOps-Automatic-Flow
on: [push]
jobs:
  automazione-cloud:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Esecuzione Comandi
        run: |
          Write-Host "Agente GitOps attivato con successo!"
          Write-Host "Leggo la configurazione attuale:"
          Get-Content manifest.txt
